<?php $this->headTitle('Dashboard'); ?>

<?php $userFeeds = $this->userPage->feeds(); ?>
<?php if(empty($userFeeds)):?>
  <div class="notice">You have no feeds on this page, use the search to add them now!</div>
<?php endif; ?>

<!-- Feeds nav -->
<div id="feeds-nav">
    <a href="javascript:;" id="add_userpage" class="l-new right">New Page</a>
    <?php echo $this->pageForm; ?>

    <?php $class = ('home' == $this->userPage->getName()) ? 'active' : ''; ?>
    <ul class="left">
      <li>
        <a class="<?= $class; ?>" href="<?php echo $this->url(array('username' => $this->authUser->getUsername(), 'page_name' => 'home'), 'dashboard'); ?>"><span>Home</span></a>
      </li>
      <?php foreach($this->authUser->pages() as $page): ?>
        <?php if('home' == $page->getName()) continue; ?>
        <?php $class = ($page->getName() == $this->userPage->getName()) ? 'active' : ''?>
        <li>
          <a class="<?= $class; ?>" href="<?php echo $this->url(array('username' => $this->authUser->getUsername(), 'page_name' => $page->getName()), 'dashboard'); ?>"><span><?php echo $page->getTitle(); ?></span></a>
        </li>
      <?php endforeach; ?>
    </ul>
    <div class="cl">&nbsp;</div>
</div>
<!-- END Feeds nav -->

<? if('home' == $this->userPage->getName() && empty($userFeeds)): ?>
  <?= $this->partial('dashboard/tutorial.phtml'); ?>
<? endif; ?>

<!-- Feed boxes -->
<div id="columns">
    <ul class="column">
      <?php foreach($userFeeds as $ufeed): ?>
      <li id="uf_<?php echo $ufeed->getId(); ?>" class="widget <?php echo $ufeed->getColor(); ?> <?php echo $ufeed->getDisplayString(); ?>" data-href="<?php echo $this->url(array('feed_uuid' => $ufeed->getFeed()->getUuid()), 'feed'); ?>">
            <div class="widget-head">
                <img src="<?= $this->favicon($ufeed->getFeed()->getWebsite()); ?>" width="16" height="16" />
                <h3><?php echo $this->shortener($ufeed->getTitle(), 40); ?></h3>
            </div>
            <div class="widget-content">
              <div id="carousel_<?php echo $ufeed->getId(); ?>" class="carousel" data-href="<?php echo $this->url(array('feed_uuid' => $ufeed->getFeed()->getUuid()), 'feed'); ?>">
                <ul>
                  <!-- insert carousel items here -->
                </ul>
                <div class="cl">&nbsp;</div>
              </div>
            </div>
        </li>
      <?php endforeach; ?>
    </ul>
    <div class="cl">&nbsp;</div>
</div>
<!-- END Feed boxes -->

