<div class="tutorial">
  <h3>Welcome to your new BuzzBlaze dashboard. Let&rsquo;s get started!</h3>
  <div class="border">&nbsp;</div>
  <div class="content">
    <h5>1. Add feeds</h5>

    <p>Enter keywords or feed URLs to search and add content sources to your dashboard. </p>

    <h5>2. Customize</h5>
    <p>You can change the look of each feed and rearrange them to whatever order you like.</p>

    <h5>3. Manage</h5>
    <p>Create pages to organize your feeds and manage them in your feeds manager.</p>

    <h5>4. Share</h5>
    <p>Share your dashboard with friends and family to let them know what you&rsquo;re reading.</p>

    <p class="tr"><a href="#" class="close">I'm ready, close this!</a></p>
  </div>
  <div class="border">&nbsp;</div>
</div>
