<div class="social-links">
  <? if($this->isLogged()): ?>
    <?php $isLiked = $this->isLiked($this->feedEntry->getId()); ?>
    <a href="<?php echo $this->url(array('feedEntry->getuuid' => $this->feedEntry->getUuid()), 'entry'); ?>" class="<?= ($isLiked) ? 'like unlike unlike_entry' : 'like like_entry'; ?>"></a>
  <? endif; ?>

<?php $url = (!empty($_SERVER['HTTPS'])) ? "https://".$_SERVER['SERVER_NAME'].$_SERVER['REQUEST_URI'] : "http://".$_SERVER['SERVER_NAME'].$_SERVER['REQUEST_URI']; 
      $pos = strpos($url, '?');
      $url = substr($url, 0, $pos); 
?>

   <a href="javascript:void(0);" onclick="window.open('http://twitter.com/share?related=stanleytang%3ACo-Founder%20of%20BuzzBlaze.com&text=<?php echo $this->feedEntry->getTitle();?>&url=<?php echo $url ?>&via=buzzblaze','', 'width=550, height=300, location=no, menubar=no, status=no,toolbar=no, scrollbars=no, resizable=no')"; class="twitter notext">Twitter</a><script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>

  <a href="javascript:void(0);" onclick="window.open('http://www.facebook.com/share.php?u=<?php echo $url ?>&amp;t=<?php echo $this->feedEntry->getTitle(); ?>','', 'width=550, height=300, location=no, menubar=no, status=no,toolbar=no, scrollbars=no, resizable=no')"; class="facebook notext">Facebook</a>




  <a href="mailto:?subject=<?php echo $this->feedEntry->getTitle(); ?>" class="mail notext">Email</a>
  <div class="cl">&nbsp;</div>
</div>
