<?php
if(null === $this->username) {
  continue;
}

$class = '';
$output = null;
$fullname = $this->full_name;
if(' ' == $fullname) {
  $fullname = $this->username;
}

switch($this->event) {
  case 'join':
    $class = 'ico-profile';
    $output = '<a href="/' . $this->username . '">' . $fullname . ' joined BuzzBlaze</a>';
    break;

  case 'update_profile':
    $class = 'ico-profile';
    $output = '<a href="/' . $this->username . '">' . 'Updated: bio, location</a>';
    break;

  case 'update_profile_picture':
    $class = 'ico-profile';
    $output = '<a href="/' . $this->username . '">' . 'Updated: profile picture</a>';
    break;

  case 'like':
    $class = 'ico-like';
    $output = '<a class="feed_entry" href="/entry/' . $this->object_uuid . '">' . $this->object_title . '</a>';
    break;

  case 'add_feed':
    $class = 'ico-rss';
    $output = '<a href="/feed/' . $this->object_uuid . '">' . $this->object_title . '</a>';
    break;
}
?>

<? if(null !== $output): ?>
  <li class="<?= $class; ?>">
    <span></span> <?= $output; ?>
    <span class="small"><?= $this->relativeDate(strtotime($this->created)); ?></span>
  </li>
<? endif; ?>
