<h1 class="pagetitle">Overview</h1>
<h2 class="subtitle">About BuzzBlaze</h2>
<div class="paragraph">

  <p>
  Founded in May 2010, BuzzBlaze is a social news reader that helps people share content online with their friends. BuzzBlaze redefines the way we read news online by providing the best news reading experience on one elegant user interface - all without ever leaving the page.
  </p>

  <p>
  At the core of BuzzBlaze, is an elegant dashboard where you can enjoy a seamless reading experience without ever leaving the page. Easily organize and browse through content from all your favorite news sources at once.
  </p>

  <p>
  Social features are built-in directly into BuzzBlaze. Become a content curator by sharing content you like with your friends. Follow your friends to find out what they are reading and discover new content and media.
  </p>

  <p>
  More than just a traditional RSS reader, BuzzBlaze provides users with the best news reading experience on the web on an easy-to-use streamlined interface. Engross yourself in slick magazine-like articles and easily share them with your friends.
  </p>

  <p>
  Most importantly, BuzzBlaze is free and always will be. <? echo (isset($this->authUser)) ? '' : '<a href="#">Sign Up Today</a>!'; ?>
  </p>

</div>
