<? $this->headTitle('Advertising'); ?>

<h1 class="pagetitle">Advertising</h1>

<div class="paragraph">

  <p>
    We are always interested in partnering with companies and offering advertising opportunities. Take a minute to send us your content information with a brief summary of your interests, and we'll get back to you shortly!
  </p>
  
  <p>
    If you are interested in advertising with us, please contact at:
  </p>
  
  <p>
    <a href="mailto:info@buzzblaze.com">info@buzzblaze.com</a>
  </p>
  
</div>	
