<? $this->headTitle('Contact us'); ?>

<h1 class="pagetitle">Contact us</h1>

<div class="paragraph">

  <p>
    For ongoing updates about BuzzBlaze, please visit our <a href="#">project blog</a>. Also, do not hesitate to contact us for:
  </p>
  
  <li>Customer support and service questions</li>
  <li>Product feedback (We love feedback)</li>
  <li>Advertising or partnership opportunities</li>
  <li>Press or media inquiries</li>
  
  <p>
    Contact us at:
  </p>
  
  <p>
    <a href="mailto:info@buzzblaze.com">info@buzzblaze.com</a>
  </p>
  
</div>	
