<? $this->headTitle('People'); ?>

<h1 class="pagetitle">People</h1>

<h2 class="subtitle">Tony Chen
  <br />
  <p>Founder & Chief Executive Officer</p>
</h2>

<div class="paragraph">
  <div class="people_image">
    <img src="/images/tony_chen.png" alt="Tony Chen">
  </div>

  <p>
    Tony Chen is the CEO of BuzzBlaze. He is responsible for setting the overall direction and strategy for the company and leading the development of BuzzBlaze's products and services. Previously, Tony founded an online magazine following modern design trends that has attracted over 26,000 subscribers. He is currently studying in his senior year of high school in Hong Kong.
  </p>

</div>
<div class="cl">&nbsp;</div>
<h2 class="subtitle">Stanley Tang
  <br />
  <p>Co-founder & President</p>
</h2>

<div class="paragraph">
  <div class="people_image">
    <img src="/images/stanley_tang.png" alt="Stanley Tang">
  </div>
  <p>
    Stanley Tang is the President at BuzzBlaze. He is responsible for setting the product strategy and driving the userbase expansion of BuzzBlaze through products, marketing and virality. Stanley is also the author of eMillions, a best-selling book on internet entrepreneurship. He is currently a freshmen at Stanford University, majoring in engineering with a focus on computer science.
  </p>

</div>
<div class="cl">&nbsp;</div>
<h2 class="subtitle">Jeongseuk Louis Kang
  <br />
  <p>Chief Financial Officer</p>
</h2>

<div class="paragraph">
  <div class="people_image">
    <img src="/images/louis_kang.png" alt="Louis Kang">
  </div>
  <p>
    Louis Kang is the Chief Financial Officer at BuzzBlaze, where he is in charge of overseeing the financial aspects and business development of the company. Prior to joining BuzzBlaze, Louis founded the Hong Kong Youth Environmental Awareness (HKYEA) group. He is currently taking a gap year.
  </p>

</div>
<div class="cl">&nbsp;</div>
<h2 class="subtitle">Joshua Lam
  <br />
  <p>External Advisor</p>
</h2>

<div class="paragraph">
  <div class="people_image">
    <img src="/images/josh_lam.png" alt="Josh Lam">
  </div>
  <p>
    Joshua Lam is a business advisor to BuzzBlaze, where he actively contributes to product development. He is a social media enthusiast and blogger. Josh is currently enrolled at University of Hong Kong studying architecture.
  </p>

</div>
