<? $this->headTitle('Press'); ?>

<h1 class="pagetitle">Press</h1>

<div class="paragraph">

  <p>
   If you are a member of the press/media, we would love to get in touch with you! We can also send you a private beta invite. All the founders are available for interview requests.
  </p>

<p>We have been featured on:</p>

<table width="100%" border="0" cellpadding="8">
  <tr>
    <td width="130"><a target="_blank" href="http://thenextweb.com/apps/2011/02/25/buzzblaze-a-social-web-based-rss-reader-with-a-visual-spin/"><img src="http://buzzblaze.com/images/tnwlogo.png" width="130px" height="54px"></a></td>
    <td valign="middle"><a target="_blank" href="http://thenextweb.com/apps/2011/02/25/buzzblaze-a-social-web-based-rss-reader-with-a-visual-spin/">BuzzBlaze: A social, web-based RSS reader with a visual spin</a></td>
  </tr>
  <tr>
    <td width="130"><a target="_blank" href="http://fastgush.com/socialmedia/two-17-year-olds-create-a-rss-based-social-networking-site-out-of-sheer-frustration-of-not-having-one.html"><img src="http://buzzblaze.com/images/fastgushlogo.png" width="130px" height="40px"></a></td>
    <td valign="middle"><a target="_blank" href="http://fastgush.com/socialmedia/two-17-year-olds-create-a-rss-based-social-networking-site-out-of-sheer-frustration-of-not-having-one.html">Two 17 year olds create a RSS based social networking site</a></td>
  </tr>
</table>
  <br>
  <p>
    Contact us at: <a href="mailto:info@buzzblaze.com">info@buzzblaze.com</a>
  </p>
  
  <p>
    Download our press release: <a href="http://BuzzBlaze.com/uploads/press_release.pdf">Updated March 2011</a>
  </p>
  
</div>	
