<?php

$this->headLink()
  ->appendStylesheet('/javascripts/jquery/jqueryui/css/aristo/jquery-ui-1.8rc3.custom.css');

$this->inlineScript()
  ->appendFile('/javascripts/jquery/jquery-1.4.2.min.js')
  ->appendFile('/javascripts/jquery/jqueryui/jquery-ui-1.8.4.custom.min.js')
  ->appendFile('/javascripts/jquery/jquery.jeditable.mini.js')
  ->appendFile('/javascripts/settings.js')
  ->appendFile('/javascripts/application.js');

