<?php

$this->headLink()
  ->appendStylesheet('/javascripts/jquery/jqueryui/css/redmond/jquery-ui-1.8.8.custom.css')
  ->appendStylesheet('/javascripts/jquery/fancybox/jquery.fancybox-1.3.4.css');

// inline script
$this->inlineScript()
  ->appendFile('/javascripts/jquery/jquery-1.4.4.min.js')
  ->appendFile('/javascripts/jquery/jqueryui/jquery-ui-1.8.8.custom.min.js')
  ->appendFile('/javascripts/jquery/jquery.vticker-min.js')
  ->appendFile('/javascripts/jquery/jquery.easing-1.3.pack.js')
  ->appendFile('/javascripts/jquery/jquery.mousewheel-3.0.4.pack.js')
  ->appendFile('/javascripts/cufon/cufon-yui.js')
  ->appendFile('/javascripts/cufon/HelveticaNeue_LTStd_BdCn.font.js')
  ->appendFile('/javascripts/cufon/HelveticaNeue_LTStd_Cn.font.js')
  ->appendFile('/javascripts/cufon/HelveticaNeue_LTStd_Roman.font.js')
  ->appendFile('/javascripts/cufon/HelveticaNeue_LTStd_Md.font.js')
  ->appendFile('/javascripts/cufon/cufon-func.js')
  ->appendFile('/javascripts/jquery/jquery.jcarousel.min.js')
  ->appendFile('/javascripts/jquery/fancybox/jquery.fancybox-1.3.4.pack.js')
  ->appendFile('/javascripts/functions.js')
  ->appendFile('/javascripts/panels.js')
  ->appendFile('/javascripts/application.js');

