<?php

$this->headScript()->prependFile(
  'http://html5shiv.googlecode.com/svn/trunk/html5.js',
  'text/javascript',
  array('conditional' => 'IE')
);

$this->headStyle()->prependStyle(
  'article, aside, dialog, figure, footer, header, hgroup, nav, section { display: block; }'
);

// favicon
$this->headLink(array(
  'rel' => 'shortcut icon', 'href' => '/favicon.ico', 'type' => 'image/x-icon'
));

$this->headLink()
  ->appendStylesheet('/stylesheets/ie6.css', 'all', 'IE')
  ->appendStylesheet('/stylesheets/style.css', 'all');
