<ul>
  <li class="<?= $this->activeNav('/overview'); ?>"><a href="/overview"><span>Overview</span></a></li>
  <li class="<?= $this->activeNav('/people'); ?>"><a href="/people"><span>People</span></a></li>
  <li class="<?= $this->activeNav('/press'); ?>"><a href="/press"><span>Press</span></a></li>
  <li class="<?= $this->activeNav('/advertising'); ?>"><a href="/advertising"><span>Advertising</span></a></li>
  <li class="<?= $this->activeNav('/contact'); ?>"><a href="/contact"><span>Contact us</span></a></li>
</ul>
