<?php
$class = '';
$output = null;

$fullname = $this->model->full_name;
if(' ' == $fullname) {
  $fullname = $this->model->username;
}

switch($this->model->event) {
  case 'like':
    $class = 'ico-like';
    $output = 'likes <a onclick="bblightbox(this); return false;" class="feed_entry" href="/entry/' . $this->model->object_uuid . '">' . $this->model->object_title . '</a>';
    break;

  case 'add_feed':
    $class = 'ico-rss';
    $output = 'added <a href="/feed/' . $this->model->object_uuid . '">' . $this->model->object_title . '</a>'
      . ' to his/her dashboard';
    break;
}

?>

<? if(null !== $output): ?>
  <li class="<?= $class; ?>">
    <span></span>
    <a href="/<?= $this->model->username; ?>"><?= $fullname; ?></a> <?= $output; ?>
    <span class="small"><?= $this->relativeDate(strtotime($this->model->created)); ?></span>
  </li>
<?php else: ?>
  <h3>Follow your friends to see what’s Buzzing!</h3>
<? endif; ?>
