<? $title = (isset($this->q)) ? 'Search for "' . $this->q . '"' : 'Search'; ?>
<? $this->headTitle($title); ?>

<?php echo $this->partial('search/_search_menu.phtml', array('q' => $this->q, 'active' => $this->active)); ?>

<div id="content-inner" class="right">
  <h1 class="pagetitle">Articles Search</h1>

  <!-- Feed search -->
  <div id="search" class="small">
    <form action="" method="post">
      <div>
        <span class="field small-field left">
          <input type="text" class="blink" name="" value="<?php echo (isset($this->q)) ? $this->q : 'Search articles'; ?>" title="Search articles" />
        </span>
        <input type="submit" class="btn-go notext left" name="" value="Go" />
        <div class="cl">&nbsp;</div>
      </div>
    </form>
  </div>
  <!-- END Feed search -->

  <h2 class="title">Results</h2>
  <ul class="results-list dynamic-list">
    <? foreach($this->paginator as $hit): ?>
      <? if(null === $hit['entry_uuid']) continue; ?>
      <li>
        <a href="<?php echo $this->url(array('entry_uuid' => $hit['entry_uuid']), 'entry'); ?>" class="feed_entry">
          <img src="<?= $this->favicon($hit['feed_website']); ?>" width="16" height="16" class="left favicon" />
        </a>
        <div class="content">
          <p><a href="<?php echo $this->url(array('entry_uuid' => $hit['entry_uuid']), 'entry'); ?>" class="feed_entry"><?php echo $hit['entry_title']; ?></a></p>
          <p class="meta">
            <a class="source" href="<?= $this->url(array('feed_uuid' => $hit['feed_uuid']), 'feed'); ?>"><?= parse_url($hit['feed_website'], PHP_URL_HOST); ?></a> -
            <?= $this->shortener(strip_tags($hit['entry_description']), 200); ?>
          </p>
        </div>
      </li>
    <? endforeach; ?>
  </ul>

  <?php echo $this->paginationControl($this->paginator, 'Sliding', '_partial/search_pagination.phtml'); ?>
</div>

