<? $title = (isset($this->q)) ? 'Search people for "' . $this->q . '"' : 'Search'; ?>
<? $this->headTitle($title); ?>

<?php echo $this->partial('search/_search_menu.phtml', array('q' => $this->q, 'active' => $this->active)); ?>

<div id="content-inner" class="right">
  <h1 class="pagetitle">People Search</h1>

  <!-- Feed search -->
  <div id="search" class="small">
    <form action="" method="post">
      <div>
        <span class="field small-field left">
          <input type="text" class="blink" name="" value="<?php echo (isset($this->q)) ? $this->q : 'Search people'; ?>" title="Search people" />
        </span>
        <input type="submit" class="btn-go notext left" name="" value="Go" />
        <div class="cl">&nbsp;</div>
      </div>
    </form>
  </div>
  <!-- END Feed search -->

  <h2 class="title">Results</h2>
  <ul class="friends-list dynamic-list">
    <? foreach($this->paginator as $hit): ?>
      <?= $this->partialLoop('_partial/userlist.phtml', $this->paginator); ?>
    <? endforeach; ?>
  </ul>

  <?php echo $this->paginationControl($this->paginator, 'Sliding', '_partial/search_pagination.phtml'); ?>
</div>

