<li>
  <span class="socials">
 <?php $url = (!empty($_SERVER['HTTPS'])) ? "https://".$_SERVER['SERVER_NAME'].$_SERVER['REQUEST_URI'] : "http://".$_SERVER['SERVER_NAME'].$_SERVER['REQUEST_URI']; 
      $pos = strpos($url, '?');
      $url = substr($url, 0, $pos); 
?>

   <a href="javascript:void(0);" onclick="window.open('http://twitter.com/share?related=stanleytang%3ACo-Founder%20of%20BuzzBlaze.com&text=<?php echo $this->feedEntry->getTitle();?>&url=<?php echo $url ?>&via=buzzblaze','', 'width=550, height=300, location=no, menubar=no, status=no,toolbar=no, scrollbars=no, resizable=no')"; class="twitter notext">Twitter</a><script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>

  <a href="javascript:void(0);" onclick="window.open('http://www.facebook.com/share.php?u=<?php echo $url ?>&amp;t=<?php echo $this->feedEntry->getTitle(); ?>','', 'width=550, height=300, location=no, menubar=no, status=no,toolbar=no, scrollbars=no, resizable=no')"; class="facebook notext">Facebook</a>
    <a href="mailto:?subject=<?php echo $this->model->getTitle(); ?>" class="ico-mail notext">Email</a>
    <? if($this->isLogged()): ?>
      <?php $isLiked = $this->isLiked($this->model->getId()); ?>
      <a onclick="like_entry(this); return false;" href="<?php echo $this->url(array('entry_uuid' => $this->model->getUuid()), 'entry'); ?>" class="<?= ($isLiked) ? 'ico-star ico-starred unlike_entry' : 'ico-star like_entry'; ?> notext">Star</a>
    <? endif; ?>
  </span>

  <? $entryThumb = $this->model->firstImage(); ?>
  <a class="feed_entry" data-permalink="<?php echo $this->model->getUrl(); ?>" title="<?= $this->model->getTitle(); ?>" id="e_<?= $this->model->getUuid(); ?>"
    href="<?php echo $this->url(array('entry_uuid' => $this->model->getUuid()), 'entry'); ?>"
    onclick="bblightbox(this); return false;">
    <img class="entry_thumb" src="<?= ('' != $entryThumb) ? $entryThumb : '/images/placeholder.gif'; ?>" style="width: 139px" alt="<?php echo $this->model->getTitle(); ?>" />
    <span class="overlay"><?php echo $this->shortener($this->model->getTitle(), 45); ?></span>
    <span class="zoom"></span>
  </a>

  <? if($this->isLogged()): ?>
    <?php $isLiked = $this->isLiked($this->model->getId()); ?>
    <a onclick="like_entry(this); return false;" href="<?php echo $this->url(array('entry_uuid' => $this->model->getUuid()), 'entry'); ?>" class="<?= ($isLiked) ? 'notext ico-star ico-starred unlike_entry' : 'notext ico-star like_entry'; ?> notext">Star</a>
  <? endif; ?>
</li>
