<?php
$errors = $this->form->getMessages();
$this->headTitle('Settings / Password');
?>

<?php echo $this->partial('settings/_settings_menu.phtml', array('active' => $this->active)); ?>

<div id="content-inner" class="right">
  <h1 class="pagetitle">Change Password</h1>
  <div class="gform_wrapper">
    <form action="" method="post">
      <div class="gform_body">
        <ul class="gform_fields">
          <li class="gfield gsection">
            <label class="gfield_label">Old password</label>
            <div class="ginput_container">
              <?php echo $this->form->getElement('old_password')->setDecorators(array(array('ViewHelper'), array('Errors')))->setAttrib('class', 'medium'); ?>
              <small><a href="<?php echo $this->url(array(), 'forgot'); ?>">Forgot your password?</a></small>
            </div>
            <div class="cl">&nbsp;</div>
          </li>

          <li class="gfield gsection">
            <label class="gfield_label">New Password</label>
            <div class="ginput_container">
              <?php echo $this->form->getElement('password')->setDecorators(array(array('ViewHelper'), array('Errors')))->setAttrib('class', 'medium'); ?>
            </div>
            <div class="cl">&nbsp;</div>
          </li>

          <li class="gfield gsection">
            <label class="gfield_label">Type it again</label>
            <div class="ginput_container">
              <?php echo $this->form->getElement('password_confirm')->setDecorators(array(array('ViewHelper'), array('Errors')))->setAttrib('class', 'medium'); ?>
            </div>
            <div class="cl">&nbsp;</div>
          </li>
        </ul>
      </div>

      <div class="gform_footer">
        <input type="submit" class="btn-save-changes" value="Save changes" title="Save changes" />
      </div>
    </form>
  </div>
</div>

